// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/prmsrswt/edu-accounts/ent/oclient"
	"github.com/prmsrswt/edu-accounts/ent/user"
)

// OClientCreate is the builder for creating a OClient entity.
type OClientCreate struct {
	config
	mutation *OClientMutation
	hooks    []Hook
}

// SetName sets the name field.
func (oc *OClientCreate) SetName(s string) *OClientCreate {
	oc.mutation.SetName(s)
	return oc
}

// SetClientID sets the clientID field.
func (oc *OClientCreate) SetClientID(s string) *OClientCreate {
	oc.mutation.SetClientID(s)
	return oc
}

// SetSecret sets the secret field.
func (oc *OClientCreate) SetSecret(s string) *OClientCreate {
	oc.mutation.SetSecret(s)
	return oc
}

// SetUserID sets the user edge to User by id.
func (oc *OClientCreate) SetUserID(id int) *OClientCreate {
	oc.mutation.SetUserID(id)
	return oc
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (oc *OClientCreate) SetNillableUserID(id *int) *OClientCreate {
	if id != nil {
		oc = oc.SetUserID(*id)
	}
	return oc
}

// SetUser sets the user edge to User.
func (oc *OClientCreate) SetUser(u *User) *OClientCreate {
	return oc.SetUserID(u.ID)
}

// Mutation returns the OClientMutation object of the builder.
func (oc *OClientCreate) Mutation() *OClientMutation {
	return oc.mutation
}

// Save creates the OClient in the database.
func (oc *OClientCreate) Save(ctx context.Context) (*OClient, error) {
	if err := oc.preSave(); err != nil {
		return nil, err
	}
	var (
		err  error
		node *OClient
	)
	if len(oc.hooks) == 0 {
		node, err = oc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oc.mutation = mutation
			node, err = oc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(oc.hooks) - 1; i >= 0; i-- {
			mut = oc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OClientCreate) SaveX(ctx context.Context) *OClient {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oc *OClientCreate) preSave() error {
	if _, ok := oc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := oc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "clientID", err: errors.New("ent: missing required field \"clientID\"")}
	}
	if _, ok := oc.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New("ent: missing required field \"secret\"")}
	}
	return nil
}

func (oc *OClientCreate) sqlSave(ctx context.Context) (*OClient, error) {
	o, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	o.ID = int(id)
	return o, nil
}

func (oc *OClientCreate) createSpec() (*OClient, *sqlgraph.CreateSpec) {
	var (
		o     = &OClient{config: oc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: oclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oclient.FieldID,
			},
		}
	)
	if value, ok := oc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oclient.FieldName,
		})
		o.Name = value
	}
	if value, ok := oc.mutation.ClientID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oclient.FieldClientID,
		})
		o.ClientID = value
	}
	if value, ok := oc.mutation.Secret(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oclient.FieldSecret,
		})
		o.Secret = value
	}
	if nodes := oc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oclient.UserTable,
			Columns: []string{oclient.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return o, _spec
}

// OClientCreateBulk is the builder for creating a bulk of OClient entities.
type OClientCreateBulk struct {
	config
	builders []*OClientCreate
}

// Save creates the OClient entities in the database.
func (ocb *OClientCreateBulk) Save(ctx context.Context) ([]*OClient, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*OClient, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				if err := builder.preSave(); err != nil {
					return nil, err
				}
				mutation, ok := m.(*OClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (ocb *OClientCreateBulk) SaveX(ctx context.Context) []*OClient {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
