// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/prmsrswt/edu-accounts/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
}
