// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
